### ISSUE TITLE
Setup playground

### ISSUE THREAD

**Issue by toshihr** [andgohq/electrumx-regtest#2]
Setup your playground.

## TODO
* [x] Set Virtual MFA to your IAM account (Authy is recommended in replace of Google Authenticator).
* [x] Run EC2 t2.medium instance with correct settings
  * Reference: bitcoin-regtest EC2 instance
  * region: northeast-1 (Tokyo) is recommended
  * new key pair
  * new Security Group
  * new elastic IP
* [x] SSH login to the instance
* [x] Install docker & docker-compose to the instance.
* [x] clone electrumx-regtest repository on the instance
* [x] run electrumx-regtest correctly on the instance ( i.e. `./test.sh` will be pass)

**Comment by MyNameIsOka** [comment]
I can't get rpctest.js to run. It always says 
`SyntaxError: Unexpected token (`
`    at exports.runInThisContext (vm.js:53:16)`
`    at Module._compile (module.js:374:25)`
`   at Object.Module._extensions..js (module.js:417:10)`
`    at Module.load (module.js:344:32)`
`    at Function.Module._load (module.js:301:12)`
`    at Function.Module.runMain (module.js:442:10)`
`    at startup (node.js:136:18)`
`    at node.js:966:3`

**Comment by toshihr** [comment]
umm, plz check at your local environment.

Reference: https://docs.docker.com/docker-for-mac/

**Comment by toshihr** [comment]
what is the version of nodejs
SyntaxError implies nodejs is old version.

**Comment by MyNameIsOka** [comment]
It seems that it's very outdated version. I will try it with the newer version.
Thank you :)
I will also try at my local machine.
